services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "${PUID}:${PGID}"
    group_add:
      - "991"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/jellyfin:/config
      - ${CONFIG_ROOT}/jellyfin-cache:/cache
      - /mnt/old-media/Filmek:/media/movies:ro
      - /mnt/old-media/Sorozatok:/media/tv:ro
    ports:
      - "${TS_IP}:8096:8096"
      - "192.168.0.167:8096:8096"
    restart: unless-stopped
    networks:
      - media

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    environment:
      - TZ=${TZ}
      - PORT=5055
    volumes:
      - ${CONFIG_ROOT}/seerr:/app/config
    ports:
      - "192.168.0.167:5055:5055"
      - "${TS_IP}:5055:5055"
    restart: unless-stopped
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "192.168.0.167:8989:8989"
      - "${TS_IP}:8989:8989"
    restart: unless-stopped
    networks:
      - media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "${TS_IP}:7878:7878"
      - "192.168.0.167:7878:7878"
    restart: unless-stopped
    networks:
      - media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - "${TS_IP}:9696:9696"
      - "192.168.0.167:9696:9696"
    restart: unless-stopped
    networks:
      - media

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "${TS_IP}:6767:6767"
      - "192.168.0.167:6767:6767"
    restart: unless-stopped
    networks:
      - media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    profiles:
      - download
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8085
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DATA_ROOT}:/data
    ports:
      - "${TS_IP}:8085:8085"
      - "192.168.0.167:8085:8085"
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    name: media-stack
